# tekartik analysis_options extension to pedantic
include: package:tekartik_common_utils/pedantic/analysis_options.strong_mode.yaml

# remove unsafe_html rules
linter:
  rules:
    unsafe_html: false
