name: 'tekartik_app_utils'
version: 0.0.8
description: App utilities
#author: Alexandre Roux Tekartik <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  platform_context:
    git: git://github.com/tekartik/platform_context.dart
  tekartik_browser_utils:
    git: git://github.com/tekartik/tekartik_browser_utils.dart
  tekartik_build_utils:
    git: git://github.com/tekartik/build_utils.dart
    version: '>=0.0.2'
  dart_to_js_script_rewriter: '>=1.0.1'
  quiver: any

dev_dependencies:
  firebase: any
  browser: '>=0.10.0'
  test: any
  dev_test: any
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart
  tekartik_bootstrap:
    git: git://github.com/tekartik/tekartik_bootstrap.dart

transformers:
- dart_to_js_script_rewriter

dependency_overrides:
#  tekartik_build_utils:
#     path: ../tekartik_build_utils.dart
  tekartik_material_asset:
#    path: ../material_asset.dart
    git: git://github.com/tekartik/material_asset.dart