name: 'tekartik_app_utils'
version: 0.0.2
description: App utilities
#author: Alexandre Roux Tekartik <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  tekartik_browser_utils:
    git: git://github.com/tekartik/tekartik_browser_utils.dart
  dart_to_js_script_rewriter: '>=1.0.1'

dev_dependencies:
  firebase3: any
  browser: '>=0.10.0'
  test: any
  dev_test: any
  chrome_travis:
     git: git://github.com/tekartik/chrome_travis.dart
transformers:
- dart_to_js_script_rewriter
