name: 'tekartik_app_utils'
version: 0.3.0
description: App utilities
#author: Alexandre Roux Tekartik <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=2.0.0-dev.63 <2.0.0'

dependencies:
  tekartik_platform_browser:
    git:
      url: git://github.com/tekartik/platform.dart
      path: platform_browser
      ref: dart2
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: dart2
    version: '>=0.2.1'
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
    version: '>=0.1.0'
  dart_to_js_script_rewriter: '>=1.0.1'
  quiver: any
  mdc: any

dev_dependencies:
  firebase: any
  browser: '>=0.10.0'
  test: any
  dev_test: any
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
  tekartik_bootstrap:
    git:
      url: git://github.com/tekartik/bootstrap.dart
      ref: dart2
  tekartik_material_asset:
    git:
      url: git://github.com/tekartik/material_asset.dart
      ref: dart2
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'