name: 'tekartik_app_utils'
version: 0.6.1
description: App utilities
publish_to: none
#author: Alexandre Roux Tekartik <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: ^3.6.0

dependencies:
  tekartik_platform_browser:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform_browser
      ref: dart3a
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
      ref: dart3a
    version: '>=0.6.8'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.6'
  tekartik_build_utils:
    git:
      url: https://github.com/tekartik/build_utils.dart
      ref: dart3a
    version: '>=0.6.5'
  js:
  web: '>=0.5.0'
dev_dependencies:
  process_run: ">=1.2.1+1"
  test: ">=1.24.0"
  dev_build: ">=1.1.0+2"
  tekartik_bootstrap:
    git:
      url: https://github.com/tekartik/bootstrap.dart
      ref: dart3a
    version: '>=0.3.0'
  tekartik_material_asset:
    git:
      url: https://github.com/tekartik/material_asset.dart
      ref: dart3a
    version: '>=0.3.3'
  build_runner: ">=2.4.13"
  build_test: '>=0.10.2'
  build_web_compilers: ">=4.0.11"

dependency_overrides:
  web: '>=1.0.0'

#  tekartik_browser_utils:
#    path: ../browser_utils.dart
