name: 'tekartik_app_utils'
version: 0.3.0
description: App utilities
#author: Alexandre Roux Tekartik <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  platform_context:
    git:
      url: git://github.com/tekartik/platform_context.dart
      ref: dart1
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: dart1
    version: '>=0.2.1'
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart1
    version: '>=0.1.0'
  dart_to_js_script_rewriter: '>=1.0.1'
  quiver: any
  mdc: any

dev_dependencies:
  firebase: any
  browser: '>=0.10.0'
  test: any
  dev_test: any
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart1
  tekartik_bootstrap:
    git:
      url: git://github.com/tekartik/bootstrap.dart
      ref: dart1
  tekartik_material_asset:
    git:
      url: git://github.com/tekartik/material_asset.dart
      ref: dart1

transformers:
- dart_to_js_script_rewriter

_dependency_overrides:
#  tekartik_build_utils:
#     path: ../tekartik_build_utils.dart
